# Generated by Django 3.2.6 on 2021-08-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_answer_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='choice_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.IntegerField(),
        ),
    ]
