# Generated by Django 3.2.6 on 2021-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210820_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice_answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(null=True),
        ),
    ]
